services:
  nginx:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: sjktest/webproject:dev   
    container_name: nginx-proxy
    ports:
      - "8080:80"
    networks:
      - joon-network

networks:
  joon-network:   
    driver: bridge