export const ENGLISH_QUOTES = [
  "The only way to do great work is to love what you do.",
  "Life is what happens when you're busy making other plans.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "The best way to predict the future is to create it.",
  "Don't watch the clock; do what it does. Keep going.",
  "You miss 100% of the shots you don't take.",
  "Whether you think you can or you think you can't, you're right.",
  "I have not failed. I've just found 10,000 ways that won't work.",
  "If you want to lift yourself up, lift up someone else.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "It does not matter how slowly you go as long as you do not stop.",
  "Everything you've ever wanted is on the other side of fear.",
  "Opportunities don't happen. You create them.",
  "Dream big and dare to fail.",
  "What you do today can improve all your tomorrows.",
  "Act as if what you do makes a difference. It does.",
  "Quality is not an act, it is a habit.",
  "With the new day comes new strength and new thoughts.",
  "The secret of getting ahead is getting started.",
  "It always seems impossible until it's done.",
  "Don't let yesterday take up too much of today.",
  "You are never too old to set another goal or to dream a new dream.",
  "If you can dream it, you can do it.",
  "The harder you work for something, the greater you'll feel when you achieve it.",
  "Push yourself, because no one else is going to do it for you.",
  "Great things never come from comfort zones.",
  "Success doesn't just find you. You have to go out and get it.",
  "The key to success is to focus on goals, not obstacles.",
  "Sometimes we're tested not to show our weaknesses, but to discover our strengths.",
  "The only place where success comes before work is in the dictionary.",
  "Doubt kills more dreams than failure ever will.",
  "Don't be afraid to give up the good to go for the great.",
  "If you are not willing to risk the usual, you will have to settle for the ordinary.",
  "All our dreams can come true, if we have the courage to pursue them.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "Try not to become a man of success, but rather try to become a man of value.",
  "Don't be distracted by criticism. Remember—the only taste of success some people get is to take a bite out of you.",
  "The road to success and the road to failure are almost exactly the same.",
  "I find that the harder I work, the more luck I seem to have.",
  "Success is not in what you have, but who you are.",
  "The only difference between ordinary and extraordinary is that little extra.",
  "The best revenge is massive success.",
  "Success usually comes to those who are too busy to be looking for it.",
  "Don't be afraid to give up the good to go for the great.",
  "I never dreamed about success. I worked for it.",
  "Success is not how high you have climbed, but how you make a positive difference to the world.",
  "Success is not the key to happiness. Happiness is the key to success.",
  "The way to get started is to quit talking and begin doing.",
];
