name: CD

on:
  push:
    branches: [main]

env:
  working-directory: ./proxy  # Dockerfile이 있는 폴더로 변경

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: docker image 빌드 및 푸시
        run: |
          IMAGE_TAG=main
          docker build --platform linux/amd64 -t sjktest/webproject:$IMAGE_TAG .
          docker push sjktest/webproject:$IMAGE_TAG
        working-directory: ${{ env.working-directory }}